version: "3.8"

services:
  app:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.17
    restart: always
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "1759:3001"
      
networks:
  default:
    external:
      name: ProxyNet

volumes:
  uptime-kuma:
    driver: local