services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25566:25565"
    volumes:
      - "minecraft:/data"
    environment:
      EULA: "TRUE"
    restart: always

volumes:
  minecraft: {}
