services:
  actual_server:
    image: docker.io/actualbudget/actual-server:25.3.1
    ports:
      - '5008:5006'
    volumes:
      - griffiths-budget:/data
    restart: unless-stopped
    
volumes:
  griffiths-budget: {}