version: "3.4"

services:
  app:
    image: monica
    container_name: monica
    depends_on:
      - db
    ports:
      - 8065:80
    env_file:
      - ../stack.env
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - APP_URL=${APP_URL}
      - FORCE_HTTPS=${FORCE_HTTPS}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    container_name: monica-db
    env_file:
      - ../stack.env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: monica_data
  mysql:
    name: monica_db_data